feat: add new fields to recipient
fabiano-mallmann/pagarme-core-api-php pull request #1
Opened 2024-03-22 18:45 UTC by fabiano-mallmann

2024-03-25 13:04 UTC, RafaMelazzo requested changes

2024-03-26 12:39 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationAddressRequest.php
> +class CreateRegisterInformationAddressRequest implements JsonSerializable
Feito

2024-03-26 12:39 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationBaseRequest.php
> +class CreateRegisterInformationBaseRequest implements JsonSerializable
Feito

2024-03-26 12:43 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationCorporationRequest.php
> +     * @required
Feito

2024-03-26 12:44 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationCorporationRequest.php
> +        $json['founding_date']        = $this->foundingDate;
Feito

2024-03-26 12:45 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationIndividualRequest.php
> +class CreateRegisterInformationIndividualRequest extends CreateRegisterInformationBaseRequest implements JsonSerializable
Feito

2024-03-26 12:46 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationIndividualRequest.php
> +     * @required
Feito

2024-03-26 12:55 UTC, fabiano-mallmann commented on src/Models/CreateRegisterInformationIndividualRequest.php
> +     * @param string $birthdate
Feito. 
$birthdate já tinha.

2024-03-26 13:00 UTC, fabiano-mallmann commented on src/Models/GetRecipientAddressResponse.php
> +        switch (func_num_args()) {
É necessário uma condicional, pois muitas vezes ele instancia sem parâmetros antes de realizar o map, mas alterei para ser um if.

2024-03-26 13:02 UTC, fabiano-mallmann commented on src/Models/GetRecipientManagingPartnersResponse.php
> +        switch (func_num_args()) {
É necessário uma condicional, pois muitas vezes ele instancia sem parâmetros antes de realizar o map, mas alterei para ser um if.

2024-03-26 13:05 UTC, fabiano-mallmann commented on src/Models/GetRecipientPhonesResponse.php
> +        switch (func_num_args()) {
É necessário uma condicional, pois muitas vezes ele instancia sem parâmetros antes de realizar o map, mas alterei para ser um if.

2024-03-26 13:05 UTC, fabiano-mallmann commented on src/Models/GetRecipientRegisterInformationResponse.php
> +     * @required
Feito

2024-03-26 13:05 UTC, fabiano-mallmann commented on src/Models/GetRecipientRegisterInformationResponse.php
> +     * @required
Feito

2024-03-26 13:06 UTC, fabiano-mallmann commented on src/Models/GetRecipientRegisterInformationResponse.php
> +     * @required
Feito

2024-03-26 13:06 UTC, fabiano-mallmann commented on src/Models/GetRecipientRegisterInformationResponse.php
> +     * @required
Feito

2024-03-26 13:07 UTC, fabiano-mallmann commented on src/Models/GetRecipientRegisterInformationResponse.php
> +                $this->managingPartners         = func_get_arg(13);
Feito

2024-03-26 14:11 UTC, mateus-picoloto approved these changes

2024-03-26 19:27 UTC, RafaMelazzo approved these changes

2024-03-27 13:44 UTC, merged