feat: add google pay payment method
fabiano-mallmann/pagarme-core-api-php pull request #4
Opened 2024-06-03 13:51 UTC by fabiano-mallmann

2024-06-05 14:05 UTC, RafaMelazzo requested changes

2024-06-06 14:23 UTC, fabiano-mallmann commented on src/Models/CreateGooglePayPaymentRequest.php
> + * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
Ajustado

2024-06-06 16:49 UTC, RafaMelazzo approved these changes

2024-06-10 13:39 UTC, mauriciohaygert approved these changes

2024-06-10 18:50 UTC, merged